apiVersion: apps/v1

kind: Deployment

metadata:

  name: node-web-app

  labels:

    app: node-web-app

spec:

  selector:

    matchLabels:

      app: node-web-app

  replicas: 3

  template:

    metadata:

      labels:

        app: node-web-app

    spec:

      containers:

      - name: node-web-app

        image: homework/node-web-app

        ports:

        - containerPort: 8080

